apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-local
  namespace: plivo-task
provisioner: ebs.csi.aws.com
parameters:
  {}
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: false
